### PR TITLE
encode empty space with %20

### PR DESCRIPTION
**Pull request by christianhaller**
Encoding the blank spaces helps us in a postprocess step.
It would be great if you could add it to the master.

### CODE REVIEW

**Comment by janb87** [comment]
@christianhaller Could you provide more info about this post process step?

**Comment by christianhaller** [comment]
Hi @janb87 
we import the generated CSS with the @coremedia CMS.
The cms is minifying the css very destructively.
It's removing the whitespaces. That's why we need them escaped.
But I agree, we could do this with an gulp replace task.

**Comment by janb87** [comment]
Not in favor of doing this inside this plugin as it is actually a workaround for an issue with coremedia.

You could write your own gulp plugin which replaces all spaces inside the svg content with "%20" before passing it to this plugin.

``` javascript
'use strict';

var through = require('through2');

module.exports = function () {
    return through.obj(function (file, enc, cb) {
        if (file.isNull()) {
            cb(null, file);
            return;
        }

        var contents = file.contents.toString();
        var updatedContents = contents.replace(/\s/gi, "%20");
        file.contents = new Buffer(updatedContents);

        cb(null, file);
    });
};
```

You would need to run this plugin before the svgcss plugin.

**Comment by christianhaller** [comment]
Hi @janb87, thank you for the code. Great help!

**Pull request closed without merging**
