### PR TITLE
Allows using custom selector prefix for generated CSS (i.e., #%.)

### PR DESCRIPTION
**Pull request by rediris**
This is useful for using this plugin with SASS’s % placeholder selector.

### CODE REVIEW

**Comment by rediris** [comment]
Hello @janb87,
Would you be willing to merge my pull-request?

**Comment by janb87** [comment]
@rediris sure, could you also add a test for this?

**Comment by janb87** [comment]
@rediris Created new npm package (1.2.0) with this change.

**Comment by rediris** [comment]
Great! Thank you.

**Pull request merged**
